-- Highlight groups for LaTeX problematic words
vim.api.nvim_set_hl(0, "TexFirstPersonSingular", { fg = "#FF6B6B", bold = true }) -- Red
vim.api.nvim_set_hl(0, "TexFirstPersonPlural", { fg = "#FFA500", bold = true }) -- Orange
vim.api.nvim_set_hl(0, "TexSecondPerson", { fg = "#FFD700", bold = true }) -- Gold
vim.api.nvim_set_hl(0, "TexColloquial", { fg = "#DA70D6", bold = true }) -- Orchid/Purple
vim.api.nvim_set_hl(0, "TexSubjective", { fg = "#00CED1", bold = true }) -- Cyan
vim.api.nvim_set_hl(0, "TexImprecise", { fg = "#FF69B4", bold = true }) -- Hot Pink
vim.api.nvim_set_hl(0, "TexWeakVerbs", { fg = "#40E0D0", bold = true }) -- Turquoise
vim.api.nvim_set_hl(0, "TexTemporalVague", { fg = "#FFB6C1", bold = true }) -- Light Pink

vim.api.nvim_set_hl(0, "TexExpressivPlaceholder", { fg = "#FF4500", bold = true }) -- OrangeRed
vim.api.nvim_set_hl(0, "TexStylisticIssue", { fg = "#FF1493", bold = true, underline = true }) -- Deep Pink with underline

-- Highlight problematic words in .tex files (case-insensitive)
vim.api.nvim_create_autocmd("FileType", {
	pattern = "tex",
	callback = function()
		-- First person singular (Red)
		vim.fn.matchadd("TexFirstPersonSingular", "\\c\\<ich\\>")
		vim.fn.matchadd("TexFirstPersonSingular", "\\c\\<mein\\(e[nmrs]\\?\\)\\?\\>")
		vim.fn.matchadd("TexFirstPersonSingular", "\\c\\<mir\\>")
		vim.fn.matchadd("TexFirstPersonSingular", "\\c\\<mich\\>")

		-- First person plural (Orange)
		vim.fn.matchadd("TexFirstPersonPlural", "\\c\\<wir\\>")
		vim.fn.matchadd("TexFirstPersonPlural", "\\c\\<uns\\(er[enmrs]\\?\\)\\?\\>")

		-- Second person (Gold)
		vim.fn.matchadd("TexSecondPerson", "\\c\\<du\\>")
		vim.fn.matchadd("TexSecondPerson", "\\c\\<dein\\(e[nmrs]\\?\\)\\?\\>")
		vim.fn.matchadd("TexSecondPerson", "\\c\\<dir\\>")
		vim.fn.matchadd("TexSecondPerson", "\\c\\<dich\\>")

		-- Colloquial/Filler words (Purple)
		vim.fn.matchadd("TexColloquial", "\\c\\<halt\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<quasi\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<irgendwie\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<sozusagen\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<eigentlich\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<letztendlich\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<gewissermaßen\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<ziemlich\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<relativ\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<eher\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<durchaus\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<sehr\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<ganz\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<recht\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<eben\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<dann\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<absolut\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<extrem\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<total\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<völlig\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<komplett\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<vollständig\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<definitiv\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<wirklich\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<tatsächlich\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<schließlich\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<letztlich\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<grundsätzlich\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<prinzipiell\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<im Grunde\\>")
		vim.fn.matchadd("TexColloquial", "\\cim\\s\\+Grunde")
		vim.fn.matchadd("TexColloquial", "\\c\\<lediglich\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<bloß\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<nun\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<nunmehr\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<bereits\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<schon\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<noch\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<doch\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<aber\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<also\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<folglich\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<somit\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<mithin\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<daher\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<deshalb\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<deswegen\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<möglicherweise\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<eventuell\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<unter Umständen\\>")
		vim.fn.matchadd("TexColloquial", "\\cunter\\s\\+Umständen")
		vim.fn.matchadd("TexColloquial", "\\c\\<gegebenenfalls\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<vielfach\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<oftmals\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<häufig\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<zumeist\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<teilweise\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<einigermaßen\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<verhältnismäßig\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<vergleichsweise\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<annähernd\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<etwa\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<ungefähr\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<circa\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<rund\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<nahezu\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<beinahe\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<fast\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<bekanntlich\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<bekanntermaßen\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<wohlgemerkt\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<gewiss\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<freilich\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<allerdings\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<immerhin\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<jedoch\\>")
		vim.fn.matchadd("TexColloquial", "\\c\\<jedenfalls\\>")

		-- Subjective/Evaluative expressions (Cyan)
		vim.fn.matchadd("TexSubjective", "\\c\\<offensichtlich\\>")
		vim.fn.matchadd("TexSubjective", "\\c\\<klar\\>")
		vim.fn.matchadd("TexSubjective", "\\c\\<natürlich\\>")
		vim.fn.matchadd("TexSubjective", "\\c\\<selbstverständlich\\>")
		vim.fn.matchadd("TexSubjective", "\\c\\<eindeutig\\>")
		vim.fn.matchadd("TexSubjective", "\\c\\<leider\\>")
		vim.fn.matchadd("TexSubjective", "\\c\\<glücklicherweise\\>")
		vim.fn.matchadd("TexSubjective", "\\c\\<erfreulicherweise\\>")
		vim.fn.matchadd("TexSubjective", "\\c\\<sicherlich\\>")
		vim.fn.matchadd("TexSubjective", "\\c\\<zweifellos\\>")
		vim.fn.matchadd("TexSubjective", "\\c\\<offenbar\\>")

		-- Imprecise/Problematic words (Hot Pink)
		vim.fn.matchadd("TexImprecise", "\\c\\<man\\>")
		vim.fn.matchadd("TexImprecise", "\\c\\<etc\\.\\?\\>")
		vim.fn.matchadd("TexImprecise", "\\c\\<usw\\.\\?\\>")
		vim.fn.matchadd("TexImprecise", "\\c\\<könnte\\>")
		vim.fn.matchadd("TexImprecise", "\\c\\<würde\\>")
		vim.fn.matchadd("TexImprecise", "\\c\\<dürfte\\>")
		vim.fn.matchadd("TexImprecise", "\\c\\<möchte\\>")

		-- Weak/Passive verbs (Turquoise)
		vim.fn.matchadd("TexWeakVerbs", "\\c\\<machen\\>")
		vim.fn.matchadd("TexWeakVerbs", "\\c\\<tun\\>")
		vim.fn.matchadd("TexWeakVerbs", "\\c\\<tut\\>")
		vim.fn.matchadd("TexWeakVerbs", "\\c\\<geben\\>")
		vim.fn.matchadd("TexWeakVerbs", "\\c\\<bekommen\\>")
		vim.fn.matchadd("TexWeakVerbs", "\\c\\<erhalten\\>")
		vim.fn.matchadd("TexWeakVerbs", "\\c\\<erfolgen\\>")

		-- Common Anglicism (Light Pink)
		vim.fn.matchadd("TexTemporalVague", "\\c\\<macht Sinn\\>")
		vim.fn.matchadd("TexTemporalVague", "\\cmacht\\s\\+Sinn")

		-- Expressiv placeholders (OrangeRed)
		vim.fn.matchadd("TexExpressivPlaceholder", "\\c\\XXX\\>")
		vim.fn.matchadd("TexExpressivPlaceholder", "\\c\\YYY\\>")

		-- Stylistic issues: "das das" (Red on Yellow)
		vim.fn.matchadd("TexStylisticIssue", "\\c\\<das\\s\\+das\\>")
	end,
})
